### PR TITLE
Quick fix for Groningen

### PR DESCRIPTION
**Pull request by yohank94**

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
@yohank94 there seems to be an issue with this. it errored in Travis

**Comment by AndyatFocallocal** [comment]
@yohank94 possibly related. I created this activity, but i can't edit it: https://focallocal.org/page/5sinAwFXPnw6d25nq

**Comment by AndyatFocallocal** [comment]
@yohank94 is it possible that pages created before the 'edit' button was added to the code, still apear without the button?

**Comment by AndyatFocallocal** [comment]
if so it's not that important. i just wanted to change the date on International Pillow Fight Day in London and Groningen, as it's set wrong on both

**Comment by AndyatFocallocal** [comment]
ah, @yohank94 i just had a PR error. pushed the exact same code again and it went through. seems to be an intermittent bug, so it might not be your change at all. would you mind making another PR to see if it goes this time.

My question whether you know why the edit button is sometimes missing stands though :)

**Comment by yohank94** [comment]
@AndyatFocallocal Should I create another PR for this commit? Are you signed in to the account that created the event? I'm not too sure. Lemme see if I can find something.

**Comment by AndyatFocallocal** [comment]
Yes, its my account and please create a new PR. Thank you

**Comment by yohank94** [comment]
Hey @AndyatFocallocal, sorry I've been away for a while. Do you still need the PR? I can't seem to create a new PR since this one was already merged to master. Has the broken Groningen post been fixed? I can remove the fix after the post is deleted.

**Comment by roamingandy** [comment]
Tom says he'll do it later today. thanks for offering, and let me know 
any time you'd like to get coding. It's exciting, the site is good 
enough now that i'm switching part of my time to building a marketing 
team to spread it around the world.

Andy

**Comment by AndyatFocallocal** [comment]
it's gone. shall i revert this commit @yohank94 or is there a better way of removing the quick fix that you'd like to add?

**Comment by yohank94** [comment]
@AndyatFocallocal I can remove it from the code and create a new PR if it makes any difference. However, I think reverting the commit would work too.

**Comment by AndyatFocallocal** [comment]
@yohank94 can you see it in the codebase still? if so can you take it out directly and make a new PR?

**Comment by yohank94** [comment]
@AndyatFocallocal yep. just making sure everything runs before pushing the commit.

**Pull request merged**
