### PR TITLE
added i18n, the package takes some time to install

### PR DESCRIPTION
**Pull request by Spartano**
i have added the i18n package and provided an simple example on how to use it. Now Andy should just create an .json object with all the changes that he wants using my code as an example, and paste it to the slack channel so a dev can paste it inside of the project and replace all keys in code.

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
i'm afraid i'm not familiar enough with code to be able to post all changes inside a .json object. i will need support

**Comment by Spartano** [comment]
On saturday or sunday we can do a screen share, and i will implement it



Il 16 Feb 2017 15:46, "AndyatFocallocal" <notifications@github.com> ha
scritto:

Merged #110 <https://github.com/focallocal/fl-maps/pull/110>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/focallocal/fl-maps/pull/110#event-965085498>, or mute
the thread

**Comment by AndyatFocallocal** [comment]
cool. i can do Sunday after midday. what time zone are you in?

**Comment by Spartano** [comment]
I Iive in italy. I will try to be free


Il 16 Feb 2017 20:16, "AndyatFocallocal" <notifications@github.com> ha
scritto:

**Comment by AndyatFocallocal** [comment]
I'm online from now @spartano send me a message on slack when you're avail

**Pull request merged**
