### PR TITLE
Change to google maps

### PR DESCRIPTION
**Pull request by ydaniel98**
Should complete implementation of google maps
Fixes issues #93, #5, and possibly issue #84

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
@ydaniel98 i don't see the legend on the map anymore

**Comment by AndyatFocallocal** [comment]
@ydaniel98 did the neon map not work?

**Comment by AndyatFocallocal** [comment]
@ydaniel98 legend is a little hard to see. can we make it bigger or bolder?

**Comment by ydaniel98** [comment]
@AndyatFocallocal I have not yet tried to add the neon map. I'll do that after finishing the search bar  and fixing the markers disappearing bug.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 cool. Sorry, I thought that was the same process., I've made a new issue for it

**Pull request merged**
