### PR TITLE
correct defautl name

### PR DESCRIPTION
**Pull request by KRChapman**
Same as master will now select correct category.

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
Did we resolve this PR's @KRChapman? i thought that we had but i'm not 100% sure. We do still have a few issues i flagged with brightertomorrowmap.com, where changes appear on publichappinessmovement.com, but are ignored on the other version

**Comment by KRChapman** [comment]
@AndyatFocallocal  yes It should be in I believe arty put it in. Went on vacation. Getting back into the swing of things I will double check later.

**Comment by AndyatFocallocal** [comment]
welcome back buddy. i am seeing some differences between the two platforms and i can't work out exactly where they come from as they now share a codebase. perhaps its all coming from different titles in i18n, i'm not too sure.

you can see an example here: https://publichappinessmovement.com/t/topic/1610/2

there's also the issue of it not syncing correctly with discourse, although that's a bit outside of areas you've worked on before. Arty is less active now he's got a pretty full on job, so we don't have anyone who can look into it really. I'll tag him anyway and see if he can have a look

**Comment by AndyatFocallocal** [comment]
@KRChapman the other obvious code related difference is in pages like this one: https://brightertomorrowmap.com/page/TfXDunjRkyRTzkbBT

publichappinessmovement.com now uses links, while btm is still using balloons for some unknown reason.

**Pull request closed without merging**
