### PR TITLE
Adding topic count badge to docuss balloons

### PR DESCRIPTION
**Pull request by sylque**
Implementation for feature request https://github.com/focallocal/fl-maps/issues/821.

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
@sylque we're ....finally ready with a live branch. i get told all checks have failed, likely because you built it on the previous broken branch. would you like to have a look and see?

**Comment by sylque** [comment]
@AndyatFocallocal , I've just checked: my code seems to be working fine with the latest focallocal:master. 

I don't know Travis CI, but having a look at the Job log, the error there seems to relate to a decryption problem when deploying the application, not to the code.

**Comment by AndyatFocallocal** [comment]
i've asked the guys to look at it

**Comment by AndyatFocallocal** [comment]
@sylque i think if i approve the merge it will push the broken branch you built on back over our newly fixed branch. Travis errored 5 days ago, and the branch was not fixed at that point.

**Comment by AndyatFocallocal** [comment]
@sylque that error message it's giving is one we've solved in the last day or two

**Comment by AndyatFocallocal** [comment]
@sylque ignore those last messages @TLMcNulty knows what the issue is and can fix it easily

**Comment by AndyatFocallocal** [comment]
@sylque Tom says 'Tell him to build local and I'll get the pipeline working'

**Pull request merged**
