### PR TITLE
meteor update, node-stubs and babel upgraded too

### PR DESCRIPTION
**Pull request by jmarks-joshua**
Update meteor to 1.12.2 (highest non-major update)
node-stubs to 1.2.1
babel to 7.3.1

### CODE REVIEW

**Comment by Marvelxy** [comment]
> Not sure if there are a bunch of standards I need to meet before I PR I couldn't find a PR guide on the readme, either way happy to do whatever I need to, to meet requirements.

Looks good to me. I've requested a review from @TLMcNulty

**Comment by TLMcNulty** [comment]
Took me a while to get an environment up and running to test this. 

Overall @jmarks-joshua great work. There's a lot of failing tests but that's not really on you, they were in failing states long before you started your upgrades. 

You're right we have no PR guide, I can update the templates with a few notes. Generally though it's a good idea to just fill out the description with a quick update. Your commit message is acceptable.

The only change that needs to be made to the files in this is the version string in the travis configuration, `.travis.yml`.

```
  - curl https://install.meteor.com/?release=1.6.1.1 | /bin/sh
```
->
```
  - curl https://install.meteor.com/?release=1.12.2 | /bin/sh
```

Thanks for this contribution and I'm looking forward to a major release upgrade next!

**Comment by jmarks-joshua** [comment]
Ah grand, thank you. 

All makes sense. Just updated the travis file.

**Comment by AndyatFocallocal** [comment]
Just chiming in to let @jmarks-joshua know there's a roughly 10min delay for compiling via travis and so its a good idea to check the live site 15mins after a PR goes through to catch any unexpected bugs.

**Pull request merged**
