### PR TITLE
"Users typing a location to search manually, doesn't work" fixed #872

### PR DESCRIPTION
**Pull request by vermiculite**

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
@vermiculite this looks to be trying to push files from the master branch onto fl-sleeper, which would break fl-sleeper. Can you please download the fl-sleeper branch and then copy/paste only the files in your fix into fl-sleeper.

**Comment by AndyatFocallocal** [comment]
@TLMcNulty this is a mistake most devs make until they become familiar with the project. Can you think of a way we can prevent this and make everything simpler?

**Comment by vermiculite** [comment]
> @vermiculite this looks to be trying to push files from the master branch onto fl-sleeper, which would break fl-sleeper. Can you please download the fl-sleeper branch and then copy/paste only the files in your fix into fl-sleeper.

Sure can, i will hopefully get a chance to look at it tonight.

**Comment by vermiculite** [comment]
> @TLMcNulty this is a mistake most devs make until they become familiar with the project. Can you think of a way we can prevent this and make everything simpler?

Hi it is a pain and possible source of bugs. I think it might be best to have the seperate parts in a seperate repository and then have copy them over in the build script. I can take a look at the differences between the two branches later to see how feesible that would be.

**Comment by AndyatFocallocal** [comment]
@vermiculite it sounds like a good idea to me, although please run it past the #backend-security channel on Slack as they are planning out new systems now. 

There should currently be no differences outside of the i18n folder, except for the settings files, API keys, etc, in the home directory.

If there are any other differences then likely someone forgot to push their update to both separately

**Comment by AndyatFocallocal** [comment]
@vermiculite this is working perfectly on the master branch. when you get a chance please copy/paste the changes into fl-sleeper and make a new PR. 

also, i think your idea for automating this sounds great. if you want to build it please post a plan in the meteor-maps branch of slack, and if no-one has any suggestions/objections then go ahead with creating it :+1:

**Pull request closed without merging**
