### PR TITLE
Fix map error

### PR DESCRIPTION
**Pull request by codeluggage**
_This branch based on `migration-refactor` to be up to date. That branch should be merged before this one._ 

Not sure if this is an ok workaround for now, but it makes things a bit more stable.

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
@codeluggage do you know what the current status of this issue is please?

**Comment by AndyatFocallocal** [comment]
'this branch has conflicts'

**Comment by ydaniel98** [comment]
@AndyatFocallocal This is a month old PR, it's unlikely that the conflicts can be resolved.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 oh. for some reason i got a notification this morning about this so i thought it was new without looking at the date.

**Pull request closed without merging**
