### PR TITLE
Update open event details buttons to use i18n

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Updates event details buttons found in the map from 'More' to 'Open' 
- Updates to use i18n
- Includes 'Meteor' in a file where it was throwing an error

### CODE REVIEW

**Comment by petesfrench** [comment]
Any ideas why Travis is failing here? I haven't touched anything that should affect it

**Comment by AndyatFocallocal** [comment]
@petesfrench Travis needs to be setup again from the beginning tbh. We should have three live sites, for deploy-phm, deploy-btm, and master. One testing server and one for each main project. 

After an error and some down time @TLMcNulty fixed them, but since then BTM doesn't build and PHM appears to build whichever branch was most recently updated. My suspicion is that the old system wasn't fully removed and BTM i'm not sure about. 

Anyway, i wouldn't worry about it. It will still merge to the live publichappinessmovement site. 

As the branches are currently mixed up can you please make your PR to both branches deploy-phm and master?

**Comment by AndyatFocallocal** [comment]
Great job, that all looks exactly to our format. 

I've requested @Marvelxy reviews it as i wasn't expecting the `import { Meteor } from 'meteor/meteor'` change and would like him to check its needed.

**Review by Marvelxy — APPROVED** [review]
Looks good to me. Great job!

**Comment by Marvelxy** [comment]
The Meteor import is needed. I wonder how we missed it LOL 🤦‍♂️🤷‍♂️😂

**Comment by AndyatFocallocal** [comment]
I wonder how it worked without it. Great spot @petesfrench

**Comment by AndyatFocallocal** [comment]
I don't think Master is going to build. That's ok as the live site is running off of deploy-phm, so once the PR is made to that branch we should se the change go live. 

(obv we need to look into it and get the backend tidied up)

**Comment by petesfrench** [comment]
Great, thank you for the review. Sorry I wasn't able to look at this until now, I was not well last week.

**Comment by AndyatFocallocal** [comment]
Glad you're better now

**Pull request merged**
