### PR TITLE
"Users typing a location to search manually, doesn't work" fixed

### PR DESCRIPTION
**Pull request by vermiculite**

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
@vermiculite would you please copy your changes and also paste them into the fl-sleeper branch? standard procedure is to do each PR twice for each branch, but to copy and not merge into both as that would break fl-sleeper.

good work, i'll let someone more experienced than myself review it and approve

**Comment by AndyatFocallocal** [comment]
> Separated out getting the current user location from the search functionality so users can search in City or in current location. Previously once it is set it cannot change.

@vermiculite That's interesting. we have another issue where the dots on the map aren't view-able when a user zooms out. i wonder if they are related? https://imgur.com/KnTBJSX

**Comment by vermiculite** [comment]
> > Separated out getting the current user location from the search functionality so users can search in City or in current location. Previously once it is set it cannot change.
> 
> @vermiculite That's interesting. we have another issue where the dots on the map aren't view-able when a user zooms out. i wonder if they are related? https://imgur.com/KnTBJSX

That doesn't look related. It does look like fun to fix though.

**Comment by vermiculite** [comment]
> @vermiculite would you please copy your changes and also paste them into the fl-sleeper branch? standard procedure is to do each PR twice for each branch, but to copy and not merge into both as that would break fl-sleeper.
> 
> good work, i'll let someone more experienced than myself review it and approve

Hi Andy, so I should do another pull request to the fl sleeper branch. Then copy and not merge, I am not clear about that. What does that mean in concrete steps? Sorry it sounds simple but I do not know what to do.

**Comment by TLMcNulty** [comment]
Checked this out locally and ran through it. Looks good from what I saw.

**Comment by AndyatFocallocal** [comment]
@vermiculite No worries. It means that if you fix one issue and then do a PR to both branches with the branch you have been working on, other users have accidentally wiped over fl-sleeper completely with the code from master. There are some differences we want to keep, like the i18n folder. 

So it's safer to ask everyone to copy the code they created to fix the issue, then download fl-sleeper and paste it in. Then make a second PR to fl-sleeper so your code is now in both branches.

**Comment by AndyatFocallocal** [comment]
@vermiculite you would be welcome to have a go at that issue. it might be a setting in googles map api. i've recorded a screen cast of the behaviour in this issue: https://trello.com/c/I8EyfawY/437-both-key-task-urgent-pins-arent-showing-on-the-map-at-all-except-for-the-area-you-search

It is an important one as most users in this stage of launch will arrive to see an empty map where they are. Most will then be disheartened and leave. The alternative is that they see an empty map so they zoom out and see other cities/towns and countries using it, and the opposite effect happens. They'll want their home represented and be motivated instead.

**Pull request merged**
