### PR TITLE
Fl sleeper updates to focal local logo

### PR DESCRIPTION
**Pull request by kristophesankar**

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
something looks wrong here @kristophesankar, it's trying to change a lot of files. What was the change you wanted it to make in the codebase

**Comment by kristophesankar** [comment]
@AndyatFocallocal I wanted to add the changes to the focallocal.org logo to the sleeper. I tried cherry picking the commits directly

**Comment by AndyatFocallocal** [comment]
@kristophesankar that's actually a documentation issue, i'm sorry. The files in each codebase should be identical, other than the ones in the i18n folder. The logo in each branch is different and so the image url should be in i18n. If it isnt then that is why you were confused, and we should call the logo url from i18n folder, that way everyone knows it's supposed to be different. Occasionally we find differences which have accidentally been coded directly into a branch rather than stated in i18n.

This is also a good opportunity to improve the cherry picking process. Right now this PR is trying to change 55 files. It looks like you are pushing all the files from fl-sleeper into master, so there is an error in the current process.

**Comment by kristophesankar** [comment]
Ahh that's the problem! I mean to commit to fl-sleeper. Did not realize I picked the wrong branch to merge to. Will fix.

**Pull request closed without merging**
