### PR TITLE
colour code edit

### PR DESCRIPTION
**Pull request by AndyatFocallocal**

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
@Marvelxy Something going wrong here. I'm merging branch Andy2 into Deploy-PHM.

In Deploy-PHM there is no folder called EventsSection here: https://github.com/focallocal/fl-maps/tree/deploy-phm/imports/client/ui/pages/Home

In Andy2 there is: https://github.com/focallocal/fl-maps/tree/Andy2/imports/client/ui/pages/Home

If i compare them i don't see that folder at all: https://github.com/focallocal/fl-maps/compare/deploy-phm...Andy2

When i merge them its not merging that folder. Can you see why?

**Comment by Marvelxy** [comment]
In that case, we should update Deploy-PHM to the latest code base version before you do your merge request. What branch do you think has the most recent code?

**Comment by AndyatFocallocal** [comment]
This one, if it works

**Comment by AndyatFocallocal** [comment]
(Andy2)

**Comment by AndyatFocallocal** [comment]
which i'd like to merge with deploy-phm but am having some issues. I'll try again now.

**Pull request closed without merging**
