### PR TITLE
User delete resource

### PR DESCRIPTION
**Pull request by KRChapman**
Updated pull request for new-master.

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
Good effort, I'm testing now. Can you also make a PR for this for new-fl-sleeper please

**Comment by AndyatFocallocal** [comment]
Oh, wait. I can't merge this. It says there are conflicts

**Comment by AndyatFocallocal** [comment]
@KRChapman the i18n files you can simply copy the ones directly from the new-master branch. the others you'll have to compare, probably it's easiest to take your changes and add them manually to the new master branch then create a new PR

**Comment by KRChapman** [comment]
Ok will do.

**Comment by AndyatFocallocal** [comment]
well done @KRChapman :+1: 

would you please make a PR for this on the new-fl-sleeper branch too

**Comment by KRChapman** [comment]
@AndyatFocallocal 
The only thing I can think of is maybe it still had some of the code problems from the hackathon. I just looked at the commits now and all of them are from prior to the hackathon in october. I attempted to press the revert button, but I got this error "Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged".

**Comment by AndyatFocallocal** [comment]
@KRChapman this doesn't appear to be working on the live branch. would you mind making a PR and putting it into master and fl-sleeper please? (i need to use it asap).

It looks like this went into 'new-master' and then wasnt copied over to the new branches. copy/paste is safer than a merge as New Master is now quite far behind the current live branches.

Thank you

**Comment by KRChapman** [comment]
> 
> 
> @KRChapman this doesn't appear to be working on the live branch. would you mind making a PR and putting it into master and fl-sleeper please? (i need to use it asap).
> 
> It looks like this went into 'new-master' and then wasnt copied over to the new branches. copy/paste is safer than a merge as New Master is now quite far behind the current live branches.
> 
> Thank you

I will. I just got back from vacation.

**Pull request merged**
