### PR TITLE
Adding stats

### PR DESCRIPTION
**Pull request by AndyatFocallocal**
My commenting out doesn't seem to work. 

@Marvelxy I noticed you used a different method which wasn't familiar to me. Would you help me understand why the commenting out doesn't work in this PR please

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
I moved your commenting out into the 1st 7 lines to make it easy to find

**Comment by Marvelxy** [comment]
Douglas Crockford removed the ability to add comments to JSON files: 

https://en.wikipedia.org/wiki/JSON#:~:text=Comments%20were%20intentionally%20excluded%20from,which%20would%20have%20destroyed%20interoperability.%22

image

The only way to add comment is to stick to a pattern, something similar to what I did.

**Review by Marvelxy — CHANGES_REQUESTED** [review]
You can transform your comment into something like the image properties I added.

**Review by Marvelxy — COMMENTED** [review]
looks good to me.

**Review by Marvelxy — APPROVED** [review]

**Review by Marvelxy — APPROVED** [review]

**Comment by AndyatFocallocal** [comment]
> looks good to me.

...really?!

**Pull request merged**
