### PR TITLE
Spam error btn

### PR DESCRIPTION
**Pull request by ydaniel98**
Adds a spam button.

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
can we label this 'spam/inaccurate' so that it also covers resources which are no longer correct, but spam would be less intuitive for reporting them

**Comment by ydaniel98** [comment]
@AndyatFocallocal. How about this?
"Think this is spam or an error? Let us know!"

**Comment by AndyatFocallocal** [comment]
perfect, nice job :)

**Comment by AndyatFocallocal** [comment]
@ydaniel98 is is possible to also put the spam/error button on this page?
image

**Pull request merged**
