### PR TITLE
changed styles to map

### PR DESCRIPTION
**Pull request by Spartano**
changes styles as wanted and added the posibility to style it however you want.

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
i get this code: [{"stylers":[{"saturation":100},{"gamma":0.6}]}]

from here: https://snazzymaps.com/style/34/neon-world

which looks too small to be able to make the changes to the map shown. also, is there an easy way to change the hue/colour of the red colour in the nearest zoom setting?

**Comment by Spartano** [comment]
yes the code is correct, if you dont like the look just select another map
from the website, and the replace the code above.

On Tue, Feb 14, 2017 at 10:13 PM, AndyatFocallocal <notifications@github.com

**Comment by Spartano** [comment]
do you have 5 min to chat on slack?
i am tryng to implement i18n

**Comment by AndyatFocallocal** [comment]
@Spartano sorry i was on other projects for a time. i'm there now, and i18n seems to be well received by others. i don't have the code base on my laptop. i'll work out how to download it. changing the code will be easy its just downloading and re-uploading. 

i don't have any technical knowledge on Meteor so i can only help in the intended uses and vision. if that's what you want let me know, if not contact DX, Ydaniel or Pawel :)

**Comment by AndyatFocallocal** [comment]
i'm thinking that combining something like this should do it:


 [{"stylers":[{"saturation":100},{"gamma":0.6}]}]

with this:

    {
        "featureType": "landscape",
        "elementType": "geometry",
        "stylers": [
            {
                "lightness": 20
            },
            {
                "saturation": 100
            }
        ]
    },

but i'd need to set it to just fire on the furthest zoomed in window. haven't found a way to set that parameter.

**Comment by AndyatFocallocal** [comment]
or perhaps better just to tweek the Gamma on the landscape on the farthest zoomed in parameter. this map fits our community best, but that red is way over the top. 

not a priority, if its more than 5 mins to fix i'll just set it as a separate issue in the Beta Launch

**Comment by Spartano** [comment]
i didnt understand what you tryng to do with the map. what does it
mean farthest
zoomed ?
i think it's better to  go with the simplest solution for now and paste a
map that you like.

**Pull request merged**
