### PR TITLE
Added auto-reload after creating an event

### PR DESCRIPTION
**Pull request by ydaniel98**
@AndyatFocallocal I would argue that this is more of a patch, maybe it can be improved later after the Beta release. (issue #69)

### CODE REVIEW

**Comment by AndyatFocallocal** [comment]
can you elaborate please @ydaniel98

**Comment by ydaniel98** [comment]
@AndyatFocallocal Reloading the page after creating a new event can be avoided by reloading the map locally. I tried a few things to achieve this (none of them worked) but decided to go with reloading the page for now.

**Comment by mordka** [comment]
Reloading a page to fix some nasty bug is really bad approach.

**Comment by ydaniel98** [comment]
@mordka I agree, but I figured that it would be fine for a beta. Some refactoring has to be done in order to reload the map template locally.

**Pull request merged**
