### PR TITLE
"What Is" now shows on the "About Us" page fixes #640

### LINKED ISSUE #640: add 'what is' section from home page to the top of about pages as well
Some users might go direct to about, or follow a link there. The 'what is' section should appear in the 'about' section AND on the home page.

This section form the home page of both maps:
image

Also added to the top of the about pages:
https://brightertomorrowmap.com/about

you can find the i18n code here,
just switch branch to find both: https://github.com/focallocal/fl-maps/blob/fl-sleeper/imports/both/i18n/en/home.json

### PR DESCRIPTION
**Pull request by cw00dw0rd**

### CODE REVIEW

**Comment by royGil** [comment]
Hey,
I think you can just import the _SecondSection_ component into the the _About_ page no?

And also I'd like to hear your opinion about those two points:

1. __SecondSection__ contains a _Read More_ button that links to the about page so it's kinda weird that it's visible here (we are already on the about page...)

2. The grey background doesn't really fits here well.. I think it will be better if we change it to white when displayed on the about page.

If you want we can set a time and work it out together :)

**Comment by cw00dw0rd** [comment]
I thought about just doing an import but didn't want the button there. Are you aware of a good way to remove the button when on the About page?

**Comment by royGil** [comment]
Yea, what about rendering the button based on a prop from the parent component?

Something like

```javascript
// Home
<SecondSection readMore />

// About
<SecondSection />

```

and then on the SecondSection component

```javascript
{this.props.readMore && <Button className='read-more'>...</Button>}

// if readMore is true -> render Button : else -> render null
```

What do you think?

**Comment by cw00dw0rd** [comment]
I like it! [Implemented fix and pushed.](https://github.com/cw00dw0rd/fl-maps/commit/d9132bc0a3add91297e8e696ba2afa0a49bf5e94) Let me know what you think!

**Pull request closed without merging**
